package com.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProgressAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressAllPropertiesEquals(Progress expected, Progress actual) {
        assertProgressAutoGeneratedPropertiesEquals(expected, actual);
        assertProgressAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressAllUpdatablePropertiesEquals(Progress expected, Progress actual) {
        assertProgressUpdatableFieldsEquals(expected, actual);
        assertProgressUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressAutoGeneratedPropertiesEquals(Progress expected, Progress actual) {
        assertThat(actual)
            .as("Verify Progress auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressUpdatableFieldsEquals(Progress expected, Progress actual) {
        assertThat(actual)
            .as("Verify Progress relevant properties")
            .satisfies(a -> assertThat(a.getModuleCompletion()).as("check moduleCompletion").isEqualTo(expected.getModuleCompletion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressUpdatableRelationshipsEquals(Progress expected, Progress actual) {
        assertThat(actual)
            .as("Verify Progress relationships")
            .satisfies(a -> assertThat(a.getModule()).as("check module").isEqualTo(expected.getModule()))
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
