# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZjI3MjhiZWE1NDQzZTZhYTZkMDYxMTg4YTliODAwMTUwYjBiMDk4MTZkYWQ5MDIyYmJkZjRiY2NjYWU1Y2RmY2U0YTk1MTRlNWRhZGIxZDk3MDEwNTMzOTI5ZGI3MTYyZjMwOGQ5Njc5ODNmYTU4MDk4MGNjOGE0ZDhiMDFhMTQ=
