package com.crystal.kip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AnswerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnswerAllPropertiesEquals(Answer expected, Answer actual) {
        assertAnswerAutoGeneratedPropertiesEquals(expected, actual);
        assertAnswerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnswerAllUpdatablePropertiesEquals(Answer expected, Answer actual) {
        assertAnswerUpdatableFieldsEquals(expected, actual);
        assertAnswerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnswerAutoGeneratedPropertiesEquals(Answer expected, Answer actual) {
        assertThat(actual)
            .as("Verify Answer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnswerUpdatableFieldsEquals(Answer expected, Answer actual) {
        assertThat(actual)
            .as("Verify Answer relevant properties")
            .satisfies(a -> assertThat(a.getText()).as("check answer").isEqualTo(expected.getText()))
            .satisfies(a -> assertThat(a.getCorrect()).as("check correct").isEqualTo(expected.getCorrect()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnswerUpdatableRelationshipsEquals(Answer expected, Answer actual) {
        assertThat(actual)
            .as("Verify Answer relationships")
            .satisfies(a -> assertThat(a.getNextStage()).as("check nextStage").isEqualTo(expected.getNextStage()))
            .satisfies(a -> assertThat(a.getFeedback()).as("check feedback").isEqualTo(expected.getFeedback()))
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()));
    }
}
