package com.crystal.kip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConceptProgressAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConceptProgressAllPropertiesEquals(ConceptProgress expected, ConceptProgress actual) {
        assertConceptProgressAutoGeneratedPropertiesEquals(expected, actual);
        assertConceptProgressAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConceptProgressAllUpdatablePropertiesEquals(ConceptProgress expected, ConceptProgress actual) {
        assertConceptProgressUpdatableFieldsEquals(expected, actual);
        assertConceptProgressUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConceptProgressAutoGeneratedPropertiesEquals(ConceptProgress expected, ConceptProgress actual) {
        assertThat(actual)
            .as("Verify ConceptProgress auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConceptProgressUpdatableFieldsEquals(ConceptProgress expected, ConceptProgress actual) {
        assertThat(actual)
            .as("Verify ConceptProgress relevant properties")
            .satisfies(a -> assertThat(a.getCompetency()).as("check competency").isEqualTo(expected.getCompetency()))
            .satisfies(a -> assertThat(a.getImprovement()).as("check improvement").isEqualTo(expected.getImprovement()))
            .satisfies(a -> assertThat(a.getEvidenceCount()).as("check evidenceCount").isEqualTo(expected.getEvidenceCount()))
            .satisfies(a -> assertThat(a.getLastPracticedAt()).as("check lastPracticedAt").isEqualTo(expected.getLastPracticedAt()))
            .satisfies(a -> assertThat(a.getMaxQuestions()).as("check maxQuestions").isEqualTo(expected.getMaxQuestions()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConceptProgressUpdatableRelationshipsEquals(ConceptProgress expected, ConceptProgress actual) {
        assertThat(actual)
            .as("Verify ConceptProgress relationships")
            .satisfies(a -> assertThat(a.getUserProfile()).as("check userProfile").isEqualTo(expected.getUserProfile()))
            .satisfies(a -> assertThat(a.getConcept()).as("check concept").isEqualTo(expected.getConcept()));
    }
}
