package com.crystal.kip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConceptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConceptAllPropertiesEquals(Concept expected, Concept actual) {
        assertConceptAutoGeneratedPropertiesEquals(expected, actual);
        assertConceptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConceptAllUpdatablePropertiesEquals(Concept expected, Concept actual) {
        assertConceptUpdatableFieldsEquals(expected, actual);
        assertConceptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConceptAutoGeneratedPropertiesEquals(Concept expected, Concept actual) {
        assertThat(actual)
            .as("Verify Concept auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConceptUpdatableFieldsEquals(Concept expected, Concept actual) {
        assertThat(actual)
            .as("Verify Concept relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getExplanation()).as("check explanation").isEqualTo(expected.getExplanation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConceptUpdatableRelationshipsEquals(Concept expected, Concept actual) {
        assertThat(actual)
            .as("Verify Concept relationships")
            .satisfies(a -> assertThat(a.getLegalContent()).as("check legalContent").isEqualTo(expected.getLegalContent()))
            .satisfies(a -> assertThat(a.getTopic()).as("check topic").isEqualTo(expected.getTopic()));
    }
}
