package com.crystal.kip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GameAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGameAllPropertiesEquals(Game expected, Game actual) {
        assertGameAutoGeneratedPropertiesEquals(expected, actual);
        assertGameAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGameAllUpdatablePropertiesEquals(Game expected, Game actual) {
        assertGameUpdatableFieldsEquals(expected, actual);
        assertGameUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGameAutoGeneratedPropertiesEquals(Game expected, Game actual) {
        assertThat(actual)
            .as("Verify Game auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGameUpdatableFieldsEquals(Game expected, Game actual) {
        assertThat(actual)
            .as("Verify Game relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGameUpdatableRelationshipsEquals(Game expected, Game actual) {
        // empty method
    }
}
