package com.crystal.kip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GameSessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGameSessionAllPropertiesEquals(GameSession expected, GameSession actual) {
        assertGameSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertGameSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGameSessionAllUpdatablePropertiesEquals(GameSession expected, GameSession actual) {
        assertGameSessionUpdatableFieldsEquals(expected, actual);
        assertGameSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGameSessionAutoGeneratedPropertiesEquals(GameSession expected, GameSession actual) {
        assertThat(actual)
            .as("Verify GameSession auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGameSessionUpdatableFieldsEquals(GameSession expected, GameSession actual) {
        assertThat(actual)
            .as("Verify GameSession relevant properties")
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGameSessionUpdatableRelationshipsEquals(GameSession expected, GameSession actual) {
        assertThat(actual)
            .as("Verify GameSession relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()))
            .satisfies(a -> assertThat(a.getGame()).as("check game").isEqualTo(expected.getGame()));
    }
}
