package com.crystal.kip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GameProgressAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGameProgressAllPropertiesEquals(GameProgress expected, GameProgress actual) {
        assertGameProgressAutoGeneratedPropertiesEquals(expected, actual);
        assertGameProgressAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGameProgressAllUpdatablePropertiesEquals(GameProgress expected, GameProgress actual) {
        assertGameProgressUpdatableFieldsEquals(expected, actual);
        assertGameProgressUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGameProgressAutoGeneratedPropertiesEquals(GameProgress expected, GameProgress actual) {
        assertThat(actual)
            .as("Verify GameProgress auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGameProgressUpdatableFieldsEquals(GameProgress expected, GameProgress actual) {
        assertThat(actual)
            .as("Verify GameProgress relevant properties")
            .satisfies(a -> assertThat(a.getSessionsPlayed()).as("check sessionsPlayed").isEqualTo(expected.getSessionsPlayed()))
            .satisfies(a -> assertThat(a.getPerformance()).as("check performance").isEqualTo(expected.getPerformance()))
            .satisfies(a -> assertThat(a.getEvidenceCount()).as("check evidenceCount").isEqualTo(expected.getEvidenceCount()))
            .satisfies(a -> assertThat(a.getLastPlayedAt()).as("check lastPlayedAt").isEqualTo(expected.getLastPlayedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGameProgressUpdatableRelationshipsEquals(GameProgress expected, GameProgress actual) {
        assertThat(actual)
            .as("Verify GameProgress relationships")
            .satisfies(a -> assertThat(a.getGame()).as("check game").isEqualTo(expected.getGame()))
            .satisfies(a -> assertThat(a.getUserProfile()).as("check userProfile").isEqualTo(expected.getUserProfile()));
    }
}
