package com.crystal.kip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LegalContentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLegalContentAllPropertiesEquals(LegalContent expected, LegalContent actual) {
        assertLegalContentAutoGeneratedPropertiesEquals(expected, actual);
        assertLegalContentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLegalContentAllUpdatablePropertiesEquals(LegalContent expected, LegalContent actual) {
        assertLegalContentUpdatableFieldsEquals(expected, actual);
        assertLegalContentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLegalContentAutoGeneratedPropertiesEquals(LegalContent expected, LegalContent actual) {
        assertThat(actual)
            .as("Verify LegalContent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLegalContentUpdatableFieldsEquals(LegalContent expected, LegalContent actual) {
        assertThat(actual)
            .as("Verify LegalContent relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLegalContentUpdatableRelationshipsEquals(LegalContent expected, LegalContent actual) {
        // empty method
    }
}
