package com.crystal.kip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ScenarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScenarioAllPropertiesEquals(Scenario expected, Scenario actual) {
        assertScenarioAutoGeneratedPropertiesEquals(expected, actual);
        assertScenarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScenarioAllUpdatablePropertiesEquals(Scenario expected, Scenario actual) {
        assertScenarioUpdatableFieldsEquals(expected, actual);
        assertScenarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScenarioAutoGeneratedPropertiesEquals(Scenario expected, Scenario actual) {
        assertThat(actual)
            .as("Verify Scenario auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScenarioUpdatableFieldsEquals(Scenario expected, Scenario actual) {
        assertThat(actual)
            .as("Verify Scenario relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScenarioUpdatableRelationshipsEquals(Scenario expected, Scenario actual) {
        assertThat(actual)
            .as("Verify Scenario relationships")
            .satisfies(a -> assertThat(a.getStartingStage()).as("check startingStage").isEqualTo(expected.getStartingStage()))
            .satisfies(a -> assertThat(a.getTopic()).as("check topic").isEqualTo(expected.getTopic()))
            .satisfies(a -> assertThat(a.getGame()).as("check game").isEqualTo(expected.getGame()));
    }
}
