package com.crystal.kip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStageAllPropertiesEquals(Stage expected, Stage actual) {
        assertStageAutoGeneratedPropertiesEquals(expected, actual);
        assertStageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStageAllUpdatablePropertiesEquals(Stage expected, Stage actual) {
        assertStageUpdatableFieldsEquals(expected, actual);
        assertStageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStageAutoGeneratedPropertiesEquals(Stage expected, Stage actual) {
        assertThat(actual)
            .as("Verify Stage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStageUpdatableFieldsEquals(Stage expected, Stage actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStageUpdatableRelationshipsEquals(Stage expected, Stage actual) {
        assertThat(actual)
            .as("Verify Stage relationships")
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()))
            .satisfies(a -> assertThat(a.getScenario()).as("check scenario").isEqualTo(expected.getScenario()));
    }
}
