package com.crystal.kip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StageAttemptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStageAttemptAllPropertiesEquals(StageAttempt expected, StageAttempt actual) {
        assertStageAttemptAutoGeneratedPropertiesEquals(expected, actual);
        assertStageAttemptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStageAttemptAllUpdatablePropertiesEquals(StageAttempt expected, StageAttempt actual) {
        assertStageAttemptUpdatableFieldsEquals(expected, actual);
        assertStageAttemptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStageAttemptAutoGeneratedPropertiesEquals(StageAttempt expected, StageAttempt actual) {
        assertThat(actual)
            .as("Verify StageAttempt auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStageAttemptUpdatableFieldsEquals(StageAttempt expected, StageAttempt actual) {
        assertThat(actual)
            .as("Verify StageAttempt relevant properties")
            .satisfies(a -> assertThat(a.getAnsweredAt()).as("check answeredAt").isEqualTo(expected.getAnsweredAt()))
            .satisfies(a -> assertThat(a.getCorrect()).as("check correct").isEqualTo(expected.getCorrect()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStageAttemptUpdatableRelationshipsEquals(StageAttempt expected, StageAttempt actual) {
        assertThat(actual)
            .as("Verify StageAttempt relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()))
            .satisfies(a -> assertThat(a.getStage()).as("check stage").isEqualTo(expected.getStage()))
            .satisfies(a -> assertThat(a.getSelectedAnswer()).as("check selectedAnswer").isEqualTo(expected.getSelectedAnswer()))
            .satisfies(a -> assertThat(a.getGameSession()).as("check gameSession").isEqualTo(expected.getGameSession()));
    }
}
