package com.crystal.kip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TopicProgressAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopicProgressAllPropertiesEquals(TopicProgress expected, TopicProgress actual) {
        assertTopicProgressAutoGeneratedPropertiesEquals(expected, actual);
        assertTopicProgressAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopicProgressAllUpdatablePropertiesEquals(TopicProgress expected, TopicProgress actual) {
        assertTopicProgressUpdatableFieldsEquals(expected, actual);
        assertTopicProgressUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopicProgressAutoGeneratedPropertiesEquals(TopicProgress expected, TopicProgress actual) {
        assertThat(actual)
            .as("Verify TopicProgress auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopicProgressUpdatableFieldsEquals(TopicProgress expected, TopicProgress actual) {
        assertThat(actual)
            .as("Verify TopicProgress relevant properties")
            .satisfies(a -> assertThat(a.getCompetency()).as("check competency").isEqualTo(expected.getCompetency()))
            .satisfies(a -> assertThat(a.getImprovement()).as("check improvement").isEqualTo(expected.getImprovement()))
            .satisfies(a -> assertThat(a.getLastPracticedAt()).as("check lastPracticedAt").isEqualTo(expected.getLastPracticedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopicProgressUpdatableRelationshipsEquals(TopicProgress expected, TopicProgress actual) {
        assertThat(actual)
            .as("Verify TopicProgress relationships")
            .satisfies(a -> assertThat(a.getTopic()).as("check topic").isEqualTo(expected.getTopic()))
            .satisfies(a -> assertThat(a.getUserProfile()).as("check userProfile").isEqualTo(expected.getUserProfile()));
    }
}
