package com.crystal.kip.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserDetailAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailAllPropertiesEquals(UserDetail expected, UserDetail actual) {
        assertUserDetailAutoGeneratedPropertiesEquals(expected, actual);
        assertUserDetailAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailAllUpdatablePropertiesEquals(UserDetail expected, UserDetail actual) {
        assertUserDetailUpdatableFieldsEquals(expected, actual);
        assertUserDetailUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailAutoGeneratedPropertiesEquals(UserDetail expected, UserDetail actual) {
        assertThat(actual)
            .as("Verify UserDetail auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailUpdatableFieldsEquals(UserDetail expected, UserDetail actual) {
        assertThat(actual)
            .as("Verify UserDetail relevant properties")
            .satisfies(a -> assertThat(a.getUsername()).as("check username").isEqualTo(expected.getUsername()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailUpdatableRelationshipsEquals(UserDetail expected, UserDetail actual) {
        // empty method
    }
}
